// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Valenzuela Saavedra Andrés Fernando — UIDE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Verifica las credenciales y devuelve un token JWT para autenticar el resto de servicios.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticación"
                ],
                "summary": "Iniciar sesión (emite token JWT)",
                "parameters": [
                    {
                        "description": "Usuario y contraseña",
                        "name": "credenciales",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Crea una nueva cuenta (credencial) cifrando la contraseña con bcrypt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticación"
                ],
                "summary": "Registrar cuenta de acceso",
                "parameters": [
                    {
                        "description": "Datos de la cuenta",
                        "name": "cuenta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.RegistroRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/catalogo/resumen": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Informe agregado: totales de libros, recursos, disponibles y préstamos activos.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogo"
                ],
                "summary": "Resumen del catálogo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sistema"
                ],
                "summary": "Estado del servicio",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/libros": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve el catálogo completo de libros.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Libros"
                ],
                "summary": "Listar libros",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_adapter_inbound_http.LibroDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un libro nuevo en el catálogo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Libros"
                ],
                "summary": "Registrar libro",
                "parameters": [
                    {
                        "description": "Datos del libro",
                        "name": "libro",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.CrearLibroRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.LibroDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/libros/buscar": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Filtra libros por título o por autor (usa \"autor\" si viene; si no, \"titulo\").",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Libros"
                ],
                "summary": "Buscar libros",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Texto a buscar en el título",
                        "name": "titulo",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Texto a buscar en el autor",
                        "name": "autor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_adapter_inbound_http.LibroDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/libros/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Libros"
                ],
                "summary": "Obtener libro por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del libro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.LibroDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Libros"
                ],
                "summary": "Eliminar libro",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del libro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/prestamos": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra el préstamo de un recurso (libro/revista) a un usuario.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Préstamos"
                ],
                "summary": "Prestar recurso",
                "parameters": [
                    {
                        "description": "IDs de recurso y usuario",
                        "name": "prestamo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.PrestamoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.PrestamoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/prestamos/activos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista los préstamos que siguen abiertos (sin devolver).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Préstamos"
                ],
                "summary": "Préstamos activos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_adapter_inbound_http.PrestamoDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/prestamos/devolver/{recursoId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cierra el préstamo activo asociado a un recurso.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Préstamos"
                ],
                "summary": "Devolver recurso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del recurso a devolver",
                        "name": "recursoId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recursos/disponibles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista libros y revistas disponibles para préstamo (polimorfismo Recurso).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogo"
                ],
                "summary": "Recursos disponibles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_adapter_inbound_http.RecursoDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/revistas": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea una revista (otro tipo de Recurso catalogable).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogo"
                ],
                "summary": "Registrar revista",
                "parameters": [
                    {
                        "description": "Datos de la revista",
                        "name": "revista",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.CrearRevistaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.RecursoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/usuarios": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve los lectores registrados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Listar usuarios",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_adapter_inbound_http.UsuarioDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un lector nuevo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Registrar usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario",
                        "name": "usuario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.CrearUsuarioRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_inbound_http.UsuarioDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_adapter_inbound_http.AutorDTO": {
            "type": "object",
            "properties": {
                "apellido": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "pais": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.CrearLibroRequest": {
            "type": "object",
            "required": [
                "anio",
                "autorApellido",
                "autorNombre",
                "isbn",
                "titulo"
            ],
            "properties": {
                "anio": {
                    "type": "integer"
                },
                "autorApellido": {
                    "type": "string"
                },
                "autorNombre": {
                    "type": "string"
                },
                "autorPais": {
                    "type": "string"
                },
                "genero": {
                    "type": "string"
                },
                "isbn": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.CrearRevistaRequest": {
            "type": "object",
            "required": [
                "numero",
                "titulo"
            ],
            "properties": {
                "editorial": {
                    "type": "string"
                },
                "numero": {
                    "type": "integer"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.CrearUsuarioRequest": {
            "type": "object",
            "required": [
                "email",
                "nombre"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.LibroDTO": {
            "type": "object",
            "properties": {
                "anio": {
                    "type": "integer"
                },
                "autor": {
                    "$ref": "#/definitions/internal_adapter_inbound_http.AutorDTO"
                },
                "disponible": {
                    "type": "boolean"
                },
                "fechaRegistro": {
                    "type": "string"
                },
                "genero": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isbn": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.PrestamoDTO": {
            "type": "object",
            "properties": {
                "activo": {
                    "type": "boolean"
                },
                "fechaDevolucion": {
                    "type": "string"
                },
                "fechaPrestamo": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recursoId": {
                    "type": "string"
                },
                "usuarioId": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.PrestamoRequest": {
            "type": "object",
            "required": [
                "recursoId",
                "usuarioId"
            ],
            "properties": {
                "recursoId": {
                    "type": "string"
                },
                "usuarioId": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.RecursoDTO": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "disponible": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.RegistroRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "rol": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.TokenResponse": {
            "type": "object",
            "properties": {
                "expira": {
                    "type": "string"
                },
                "rol": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_inbound_http.UsuarioDTO": {
            "type": "object",
            "properties": {
                "activo": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Autenticación JWT. Escribe: \"Bearer {token}\" (obtén el token en POST /auth/login).",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "API Sistema de Gestión de Libros — Biblioteca UIDE",
	Description:      "API REST del proyecto final de POO. Catálogo de libros y revistas,\nusuarios (lectores) y préstamos, con autenticación JWT y persistencia\nCode First sobre SQL Server. La serialización es JSON.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
